#!/bin/bash
# test suit for simple_shell project
# temp

# set ./hsh with the path of your executable file
#gcc -Wall -Werror -Wextra -pedantic *.c -o hsh

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# create direcories for testing files
mkdir test_results
mkdir test_results/expected
mkdir test_results/obtained

test=
command=""
$command > test_results/expected/test$test
echo $command | ./hsh > test_results/obtained/test$test


# results
diff test_results/expected/ test_results/obtained/ > test_results/error_log
diff -qs test_results/expected/ test_results/obtained/ > test_results/error_summary

num=$(grep -c "differ" test_results/error_summary)
if [ $num == 0 ]
	then 
		echo -e "${GREEN}No errors${NC}, shell works successfully"
	else
		echo -e "${RED}$num errors:${NC}"
		cat test_results/error_summary | grep "differ" | cut -f4 -d" " | cut -f3 -d"/"
		echo -e "${RED}See details of errors: ${NC}test_results/error_log"
fi
maxii2
